### ISSUE TITLE
Document public

### ISSUE THREAD

**Issue by dxcanh** [LeDat98/JSL_App_Webapp#2]
Em chào anh @LeDat98, em thấy dự án của anh rất hay và muốn build 1 model tương tự nhưng dành cho Tiếng Việt. Anh có thể cho em xin 1 số tài liệu để a build model này được không ạ, cũng như là 1 vài bộ datasets ạ. Em cảm ơn anh nhiều ạ.

**Comment by LeDat98** [comment]
Chào e e có nick facebook ? Hoặc e có thể gửi tn vào tk này cho mình dễ nc https://www.facebook.com/leducdat0.1/

Vào Th 7, 5 thg 10, 2024 lúc 01:11 dxcanh ***@***.***> đã
viết:

**Comment by dxcanh** [comment]
anh check phần tin nhắn chờ giúp em với ạ
